### ISSUE TITLE
Wrong syntax highlighting for minifed css file where code is after closing comment

### ISSUE THREAD

**Issue by jcubic** [textmate/css.tmbundle#26] opened 2016-06-17 19:16 UTC
I have minified css file that is not highlighted correctly, the whole file is mark as comment, here is [sample using lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftextmate%2Fcss.tmbundle%2F94f7111c2953ac7b4cc42d313d9ad9b8701b8468%2FSyntaxes%2FCSS.plist&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fjcubic%2Fjquery.terminal%2Fmaster%2Fcss%2Fjquery.terminal.min.css&code=).

**Comment by infininight** [comment] 2016-08-26 09:21
OK, you can get confirmation from Github on this issue but I believe I know the cause. There is nothing wrong with the grammar itself, the same code snippet parses in TextMate just fine. It appears that GitHub's parser has a time limit or length limit per-line before the parser cancels out and returns the line unparsed. So it's not actually matching as a comment it just never gets closed as that is on the line with the rest of the CSS.

You can verify this by having a short snippet of one line CSS that matches fine, keep duplicating it on the end and it will eventually stop being matched.

**Closed by infininight** 2016-08-26 09:21 UTC

**Comment by jcubic** [comment] 2016-08-26 10:10
So what sould github do with this?
